resources:
- ns.yaml
- database.yaml
- pooler-ss-rw-svc.yaml
- pooler-tx-rw-svc.yaml
- backup.yaml

secretGenerator:
- name: rucio-db-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret

- name: rucio-db-pg-monitor
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
  - etc/.secrets/url

namespace: rucio-db-prod
