
namespace: rucio

resources:
- ns.yaml
- helm-rucio-server.yaml
#- helm-rucio-daemons.yaml
#- helm-rucio-ui.yaml

patchesStrategicMerge:
- patch-ingress.yaml
#- grid-certificates-patch.yaml
#- hermesk-image-patch.yaml

secretGenerator:
# rucio
- name: usdf-db-conn-str
  files:
  - db-conn-str.txt=etc/.secrets/db-conn-str.txt

- name: usdf-server-hostcert
  files:
  - hostcert.pem=etc/.secrets/hostcert.pem
- name: usdf-server-hostkey
  files:
  - hostkey.pem=etc/.secrets/hostkey.pem
- name: usdf-server-cafile
  files:
  - ca.pem=etc/.secrets/ca.pem

- name: usdf-rucio-x509up
  files:
  - hostcert.pem=etc/.secrets/hostcert.pem
  - hostkey.pem=etc/.secrets/hostkey.pem
  options:
    disableNameSuffixHash: true

- name: usdf-rucio-ca-bundle
  files:
  - ca.pem=etc/.secrets/ca.pem
  options:
    disableNameSuffixHash: true
- name: usdf-rucio-ca-bundle-reaper
  files:
  - ca.pem=etc/.secrets/ca.pem
  options:
    disableNameSuffixHash: true

# ingress
- name: rucio-server.tls-secret
  files:
  - cert=etc/.secrets/hostcert.pem
  - key=etc/.secrets/hostkey.pem

# webui
- name: usdf-hostcert
  files:
  - hostcert.pem=etc/.secrets/hostcert.pem
- name: usdf-hostkey
  files:
  - hostkey.pem=etc/.secrets/hostkey.pem
- name: usdf-cafile
  files:
  - ca.pem=etc/.secrets/ca.pem

# fts3
- name: usdf-fts-cert
  files:
  - usercert.pem=etc/.secrets/hostcert.pem
- name: usdf-fts-key
  files:
  - new_userkey.pem=etc/.secrets/hostkey.pem

# lsst customization
- name: usdf-lsst-schema-file
  files:
  - lsst.py=etc/lsst.py
  options:
    disableNameSuffixHash: true

# automatix input
- name: usdf-rucio-automatix-input-file
  files:
  - automatix.json=etc/.secrets/automatix.json
  options:
    disableNameSuffixHash: true
- name: usdf-hermeskafka-constants
  files:
  - constants.py=etc/constants.py
  options:
    disableNameSuffixHash: true
